apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Echo -n "postgresql://user:password@host:port/db" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdDozNDU2L2RiCg==
