name: Backend CI/CD Pipeline

on:
  pull_request:
    branches: [ "main" ] #se activa en la main cuando se hace un pull en main, si eliminamos esto puede que fucionemos un codigo roto 
  push:
    branches: [ "main" ] #si se elimina esto no se hara el despliegue automatico 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} #agrupa las ejecuciones del mismo workflow y reference
  cancel-in-progress: true #cancela las ejecuciones anteriores si se produce una nueva, es para evitar perdida de tiempo , si se cambia esto a false correra todo al mismo tiempo y puede generar incosistencias
#si diggaos hacemos varios commits seguidos se haran en paralelo y pues esto puede hacer colgar los servicios y dejar una version antigua 
permissions:
  contents: read #si se le pone none la descarga del checkout no se podra realizar

jobs: #1er job
  validate:
    name: Validation & Build 
    runs-on: ubuntu-latest #si se cambia a windows tarddara mas 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #clona el repo

      - name: Setup Node.js
        uses: actions/setup-node@v4 #npm install 
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client #generar prisma bd local
        run: npx prisma generate

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build #crea la carpeta dist 

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4 #valida todo antes de mandarlo al sig job 
        with:
          name: backend-dist
          path: dist/

  deploy: #2do job
    name: Deploy to Production
    needs: validate #si se quita faallara porque correra en paralelo
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://saludtotal-backend-gpcs.onrender.com
      
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4 #descarga todo lo validado anteriormente 
        with:
          name: backend-dist
          path: dist/

      - name: Trigger Deployment
        run: |
          echo "Deploying Backend to Production environment..."
          echo "Deployment is triggered automatically via Render webhook on push to main."
